## Pandas Basics

In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\hetan\miniconda3\envs\new_env\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hetan\miniconda3\envs\new_env\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\hetan\miniconda3\envs\new_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   --------- ------------------------------ 2.4/10.0 MB 12.2 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.0 MB 11.2 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/10.0 MB 11.5 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 10.0 MB/s  0:00:01
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.3

In [4]:
import pandas as pd

## Creating DataFrame

In [5]:
salesData = {
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "customer": ["Hetanshi", "Prisha", "Riddhima", "Soha", "Divya", "Dhvani", "Suhani", "Heer"],
    "product": ["Laptop", "Mouse", "Keyboard", "Laptop", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "category": ["Electronics", "Accessories", "Accessories", "Electronics",
                 "Electronics", "Accessories", "Accessories", "Electronics"],
    "quantity": [1, 2, 1, 2, 1, 3, 2, 1],
    "price": [800, 25, 50, 800, 800, 50, 25, 200]
}

df = pd.DataFrame(salesData)
df

   order_id  customer   product     category  quantity  price
0       101  Hetanshi    Laptop  Electronics         1    800
1       102    Prisha     Mouse  Accessories         2     25
2       103  Riddhima  Keyboard  Accessories         1     50
3       104      Soha    Laptop  Electronics         2    800
4       105     Divya    Laptop  Electronics         1    800
5       106    Dhvani  Keyboard  Accessories         3     50
6       107    Suhani     Mouse  Accessories         2     25
7       108      Heer   Monitor  Electronics         1    200

In [6]:
df.head()

   order_id  customer   product     category  quantity  price
0       101  Hetanshi    Laptop  Electronics         1    800
1       102    Prisha     Mouse  Accessories         2     25
2       103  Riddhima  Keyboard  Accessories         1     50
3       104      Soha    Laptop  Electronics         2    800
4       105     Divya    Laptop  Electronics         1    800

In [8]:
df.shape

(8, 6)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      int64
 1   customer  8 non-null      str
 2   product   8 non-null      str
 3   category  8 non-null      str
 4   quantity  8 non-null      int64
 5   price     8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 516.0 bytes

In [10]:
df.describe()

        order_id  quantity       price
count    8.00000  8.000000    8.000000
mean   104.50000  1.625000  343.750000
std      2.44949  0.744024  381.900791
min    101.00000  1.000000   25.000000
25%    102.75000  1.000000   43.750000
50%    104.50000  1.500000  125.000000
75%    106.25000  2.000000  800.000000
max    108.00000  3.000000  800.000000

## Performing Operations

In [11]:
df[["product", "price"]]

    product  price
0    Laptop    800
1     Mouse     25
2  Keyboard     50
3    Laptop    800
4    Laptop    800
5  Keyboard     50
6     Mouse     25
7   Monitor    200

In [12]:
df.iloc[0:3]

   order_id  customer   product     category  quantity  price
0       101  Hetanshi    Laptop  Electronics         1    800
1       102    Prisha     Mouse  Accessories         2     25
2       103  Riddhima  Keyboard  Accessories         1     50

## Filtering

In [13]:
df[df["product"] == "Laptop"]

   order_id  customer product     category  quantity  price
0       101  Hetanshi  Laptop  Electronics         1    800
3       104      Soha  Laptop  Electronics         2    800
4       105     Divya  Laptop  Electronics         1    800

In [14]:
df[(df["quantity"] > 1) & (df["category"] == "Accessories")]

   order_id customer   product     category  quantity  price
1       102   Prisha     Mouse  Accessories         2     25
5       106   Dhvani  Keyboard  Accessories         3     50
6       107   Suhani     Mouse  Accessories         2     25

In [16]:
df["total"] = df["quantity"] * df["price"]
df

   order_id  customer   product     category  quantity  price  total
0       101  Hetanshi    Laptop  Electronics         1    800    800
1       102    Prisha     Mouse  Accessories         2     25     50
2       103  Riddhima  Keyboard  Accessories         1     50     50
3       104      Soha    Laptop  Electronics         2    800   1600
4       105     Divya    Laptop  Electronics         1    800    800
5       106    Dhvani  Keyboard  Accessories         3     50    150
6       107    Suhani     Mouse  Accessories         2     25     50
7       108      Heer   Monitor  Electronics         1    200    200

## Soring

In [17]:
df.sort_values("total", ascending=False)

   order_id  customer   product     category  quantity  price  total
3       104      Soha    Laptop  Electronics         2    800   1600
0       101  Hetanshi    Laptop  Electronics         1    800    800
4       105     Divya    Laptop  Electronics         1    800    800
7       108      Heer   Monitor  Electronics         1    200    200
5       106    Dhvani  Keyboard  Accessories         3     50    150
1       102    Prisha     Mouse  Accessories         2     25     50
2       103  Riddhima  Keyboard  Accessories         1     50     50
6       107    Suhani     Mouse  Accessories         2     25     50

## Missing data

In [18]:
df.loc[2, "price"] = None

In [19]:
df.isnull().sum()

order_id    0
customer    0
product     0
category    0
quantity    0
price       1
total       0
dtype: int64

In [20]:
df["price"] = df["price"].fillna(50)

In [21]:
df.isnull().sum()

order_id    0
customer    0
product     0
category    0
quantity    0
price       0
total       0
dtype: int64

## Aggregation, Group BY

In [22]:
df.groupby("customer")["total"].sum()

customer
Dhvani       150
Divya        800
Heer         200
Hetanshi     800
Prisha        50
Riddhima      50
Soha        1600
Suhani        50
Name: total, dtype: int64

In [23]:
df.groupby("customer")["total"].mean()

customer
Dhvani       150.0
Divya        800.0
Heer         200.0
Hetanshi     800.0
Prisha        50.0
Riddhima      50.0
Soha        1600.0
Suhani        50.0
Name: total, dtype: float64

In [24]:
df.groupby("product")["quantity"].sum()

product
Keyboard    4
Laptop      4
Monitor     1
Mouse       4
Name: quantity, dtype: int64

Reference: [Pandas documentation](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html)